from dataclasses import dataclass

from xdsl.dialects import builtin, memref, func, arith, scf, llvm
from xdsl.dialects.builtin import i8, StringAttr, DYNAMIC_INDEX, IndexType, IntegerAttr
from xdsl.context import Context
from xdsl.passes import ModulePass
from xdsl.ir import Block, Region
from xdsl.utils.hints import isa

from xdsl_ccpp.dialects import ccpp_utils
from xdsl_ccpp.dialects.ccpp_utils import ArraySectionOp, StringEqOp, HostVarRefOp, WriteErrMsgOp

from xdsl_ccpp.transforms.util.ccpp_descriptors import BuildMetaDataDescriptions, BuildSchemeDescription, CCPPType
from xdsl_ccpp.transforms.util.typing import TypeConversions


@dataclass(frozen=True)
class CCPPCAP(ModulePass):
    """MLIR pass that generates the CCPP physics cap dispatcher module.

    Runs after generate-suite-cap.  For each suite found in the ccpp module,
    generates lifecycle dispatcher subroutines that:
      1. Take ``suite_name`` (assumed-length character), ``errmsg``, and
         ``errflg`` as arguments.
      2. Compare ``suite_name`` against the suite's name literal.
      3. If the name matches, delegate to the corresponding suite cap
         subroutine (generated by generate-suite-cap).

    Currently generates ``_initialize`` and ``_finalize`` dispatchers.
    Output is a named ModuleOp (e.g. ``hello_world_ccpp_cap``) inserted into
    the top-level module alongside the suite cap modules.
    """

    name = "generate-ccpp-cap"

    def find_ccpp_module(self, ops):
        """Return the named 'ccpp' ModuleOp from the given op list, or None."""
        for op in ops:
            if isa(op, builtin.ModuleOp) and op.sym_name is not None and op.sym_name.data == "ccpp":
                return op
        return None

    def _collect_public_suite_functions(self, ops):
        """Scan all named ModuleOps in ops and return a map of public function info.

        Looks at every named sub-ModuleOp (e.g. ``hello_world_suite_cap``) that
        is already present in the IR (generated by earlier passes) and records
        every public subroutine definition it contains.

        Returns:
            dict mapping function_name → (module_name, output_types,
            input_types, input_names) where output_types and input_types are
            lists of MLIR types and input_names is the list of block arg
            name_hints.  Used to resolve callee module names, derive return
            types, and forward physics input arguments for the run dispatcher.
        """
        public_fns = {}
        for op in ops:
            if not (isa(op, builtin.ModuleOp) and op.sym_name is not None):
                continue
            mod_name = op.sym_name.data
            for child in op.body.block.ops:
                if (
                    isa(child, func.FuncOp)
                    and not child.is_declaration
                    and child.sym_visibility is not None
                    and child.sym_visibility.data == "public"
                ):
                    public_fns[child.sym_name.data] = (
                        mod_name,
                        list(child.function_type.outputs),
                        list(child.function_type.inputs),
                        [arg.name_hint for arg in child.body.block.args],
                    )
        return public_fns

    def _derive_camel_case_name(self, suite_name: str) -> str:
        """Convert a snake_case suite name to CamelCase, stripping any '_suite' suffix.

        Examples:
            hello_world_suite → HelloWorld
            my_suite          → My
        """
        name = suite_name
        if name.endswith("_suite"):
            name = name[:-6]
        return "".join(word.capitalize() for word in name.split("_"))

    def _get_suite_lifecycle_return_types(self, scheme_names, meta_data, table_postfix):
        """Derive the ordered return types of a suite lifecycle subroutine.

        Mirrors the alloc_ops ordering that generate-suite-cap uses: iterates
        out args from each scheme's arg table (identified by ``table_postfix``,
        e.g. ``"_init"`` or ``"_finalize"``) in metadata order, deduplicating
        by argument name.

        Returns a list of MLIR MemRefType values (one per unique out arg).
        """
        all_out_args = {}
        for scheme_name in scheme_names:
            table_name = scheme_name + table_postfix
            assert table_name in meta_data[scheme_name].arg_tables, \
                f"No '{table_postfix}' arg table found for scheme '{scheme_name}'"
            arg_table = meta_data[scheme_name].getArgTable(table_name)
            for fn_arg in arg_table.getFunctionArguments():
                if fn_arg.getAttr("intent") == "out" and fn_arg.name not in all_out_args:
                    all_out_args[fn_arg.name] = fn_arg

        return [
            TypeConversions.convert(
                arg.getAttr("type"),
                arg.getAttr("kind") if arg.hasAttr("kind") else None,
                0,
            )
            for arg in all_out_args.values()
        ]

    def _generate_lifecycle_fn(
        self, fn_name, suite_name, suite_callee, call_ret_types,
        suite_name_type, errmsg_type, errflg_type, char_base, int_base,
        public_fns,
    ):
        """Build one CCPP cap lifecycle FuncOp and its external declaration.

        Asserts that ``suite_callee`` is listed in ``public_fns`` (the map of
        public functions collected from the already-generated suite cap modules)
        and attaches the owning module name to the external declaration as the
        ``module`` attribute.  The Fortran printer uses this to emit a
        ``use <module>, only: <proc>`` statement in the generated module.

        The generated subroutine:
          1. Allocates local errmsg and errflg.
          2. Initialises errflg = 0.
          3. Compares suite_name against the suite name literal.
          4. If they match, calls suite_callee and copies the results back.

        Returns ``(FuncOp, external_decl_FuncOp)``.
        """
        assert suite_callee in public_fns, (
            f"Suite callee '{suite_callee}' not found among public suite cap "
            f"functions; available: {sorted(public_fns)}"
        )
        callee_module, _callee_output_types, _, _ = public_fns[suite_callee]
        errmsg_alloc = memref.AllocaOp.get(char_base, shape=[512])
        errmsg_alloc.memref.name_hint = "errmsg"
        errflg_alloc = memref.AllocaOp.get(int_base, shape=[])
        errflg_alloc.memref.name_hint = "errflg"

        new_block = Block(arg_types=[suite_name_type])
        new_block.args[0].name_hint = "suite_name"

        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_alloc, [])

        string_eq_op = StringEqOp(new_block.args[0], suite_name)

        call_op = func.CallOp(suite_callee, [], call_ret_types)

        copy_ops = []
        for idx, ret_type in enumerate(call_ret_types):
            if ret_type == errmsg_type:
                copy_ops.append(memref.CopyOp(call_op.results[idx], errmsg_alloc))
            elif ret_type == errflg_type:
                copy_ops.append(memref.CopyOp(call_op.results[idx], errflg_alloc))

        write_err = WriteErrMsgOp(errmsg_alloc, new_block.args[0], "No suite named ", "found")
        one_err = arith.ConstantOp.from_int_and_width(1, 32)
        store_errflg_err = memref.StoreOp.get(one_err, errflg_alloc, [])

        if_op = scf.IfOp(
            string_eq_op.res, [],
            [call_op] + copy_ops + [scf.YieldOp()],
            [write_err, one_err, store_errflg_err, scf.YieldOp()],
        )

        ret_op = func.ReturnOp(errmsg_alloc, errflg_alloc)

        new_block.add_ops([
            errmsg_alloc, errflg_alloc,
            err_const, store_errflg,
            string_eq_op,
            if_op,
            ret_op,
        ])

        body = Region()
        body.add_block(new_block)

        fn_type = builtin.FunctionType.from_lists(
            [suite_name_type],
            [errmsg_type, errflg_type],
        )
        cap_fn = func.FuncOp(fn_name, fn_type, body, visibility="public")
        decl = func.FuncOp.external(suite_callee, [], call_ret_types)
        # Record which module owns suite_callee so the Fortran printer can
        # emit the correct 'use <module>, only: <proc>' statement.
        decl.attributes["module"] = StringAttr(callee_module)
        return cap_fn, decl

    def _generate_run_fn(
        self, fn_name, suite_name, suite_part, suite_callee,
        suite_name_type, errmsg_type, errflg_type, char_base, int_base,
        public_fns, scheme_names, meta_data,
    ):
        """Build the CCPP cap physics run FuncOp and its external declaration.

        Unlike ``_generate_lifecycle_fn``, the run function:
          1. Takes ``suite_part`` (assumed-length character) as a second
             dispatch argument after ``suite_name``.
          2. Accepts ``errmsg`` and ``errflg`` as ``intent(inout)`` block
             arguments (not local allocas).
          3. Maps physics input args to host module variables (via
             standard_name matching against MODULE-type metadata), removing
             them from the run function's argument list.  Args without a host
             mapping remain as ordinary block arguments.
          4. Emits ``llvm.GlobalOp`` stubs (with a ``module`` attribute) for
             each host variable so the Fortran printer generates the correct
             ``use <module>, only: <var>`` statements.
          5. Nests two ``StringEqOp`` comparisons: outer on ``suite_name``,
             inner on ``suite_part``.
          6. Emits ``WriteErrMsgOp`` in both else branches.

        Returns ``(FuncOp, external_decl_FuncOp, host_global_ops)``.
        """
        assert suite_callee in public_fns, (
            f"Suite callee '{suite_callee}' not found; "
            f"available: {sorted(public_fns)}"
        )
        callee_module, callee_output_types, callee_input_types, callee_input_names = (
            public_fns[suite_callee]
        )

        # ── Standard-name lookup for physics args ────────────────────────────
        # Build {local_arg_name → standard_name} from the _run arg tables.
        std_name_of = {}
        for scheme_name in scheme_names:
            table_name = scheme_name + "_run"
            if scheme_name not in meta_data:
                continue
            if table_name not in meta_data[scheme_name].arg_tables:
                continue
            for fn_arg in meta_data[scheme_name].getArgTable(table_name).getFunctionArguments():
                if fn_arg.name not in std_name_of and fn_arg.hasAttr("standard_name"):
                    std_name_of[fn_arg.name] = fn_arg.getAttr("standard_name")

        # Build {standard_name → (host_var_name, module_name)} from MODULE metadata.
        host_var_map = {}
        for tbl_name, props in meta_data.items():
            if props.getAttr("type") != CCPPType.MODULE:
                continue
            if tbl_name not in props.arg_tables:
                continue
            for var in props.getArgTable(tbl_name).getFunctionArguments():
                if var.hasAttr("standard_name"):
                    host_var_map[var.getAttr("standard_name")] = (var.name, tbl_name)

        # Classify each callee input arg as host-mapped or a plain block arg.
        # physics_arg_sources[i] = ("host", host_var_name, module_name)
        #                          or ("block",)
        physics_arg_sources = []
        for arg_name in callee_input_names:
            std_name = std_name_of.get(arg_name)
            if std_name and std_name in host_var_map:
                host_var_name, host_module_name = host_var_map[std_name]
                # Assert the host variable is actually declared in that module.
                assert host_var_name in (
                    meta_data[host_module_name].arg_tables[host_module_name].function_arguments
                ), (
                    f"Host variable '{host_var_name}' not found in "
                    f"'{host_module_name}' arg table"
                )
                physics_arg_sources.append(("host", host_var_name, host_module_name))
            else:
                physics_arg_sources.append(("block",))

        suite_part_type = suite_name_type  # also memref<?xi8>

        # Non-host physics args become block args of the run function.
        non_host_args = [
            (callee_input_names[i], callee_input_types[i])
            for i, src in enumerate(physics_arg_sources)
            if src[0] == "block"
        ]

        # Block args: suite_name, suite_part, non_host_physics_args..., errmsg, errflg
        n_non_host = len(non_host_args)
        all_block_types = (
            [suite_name_type, suite_part_type]
            + [t for _, t in non_host_args]
            + [errmsg_type, errflg_type]
        )
        new_block = Block(arg_types=all_block_types)

        suite_name_arg = new_block.args[0]
        suite_name_arg.name_hint = "suite_name"
        suite_part_arg = new_block.args[1]
        suite_part_arg.name_hint = "suite_part"

        block_arg_map = {}
        for i, (arg_name, _) in enumerate(non_host_args):
            ba = new_block.args[2 + i]
            ba.name_hint = arg_name
            block_arg_map[arg_name] = ba

        errmsg_arg = new_block.args[2 + n_non_host]
        errmsg_arg.name_hint = "errmsg"
        errflg_arg = new_block.args[2 + n_non_host + 1]
        errflg_arg.name_hint = "errflg"

        # ── HostVarRefOps and GlobalOp stubs for host-mapped args ─────────────
        # One HostVarRefOp per host-mapped arg (placed in the main block so it
        # is in scope for the nested CallOp).  One llvm.GlobalOp stub (with a
        # 'module' attribute) per unique (host_var_name, module_name) pair so
        # the printer generates 'use <module>, only: <var>' in the preamble.
        host_var_ref_ops = []
        host_var_ref_results = {}   # arg_name → SSA value
        host_global_ops = []
        seen_host_globals: set = set()

        # Reverse map: host_var_name → SSA result of its HostVarRefOp.
        # Built alongside host_var_ref_results so that ArraySectionOps can
        # look up bound variables (e.g. "pverp") by their host variable name.
        host_name_to_ref_result = {}

        for i, (arg_name, arg_type) in enumerate(zip(callee_input_names, callee_input_types)):
            src = physics_arg_sources[i]
            if src[0] != "host":
                continue
            _, host_var_name, host_module_name = src
            ref_op = HostVarRefOp(host_var_name, host_module_name, arg_type)
            host_var_ref_ops.append(ref_op)
            host_var_ref_results[arg_name] = ref_op.res
            host_name_to_ref_result[host_var_name] = ref_op.res

            key = (host_var_name, host_module_name)
            if key not in seen_host_globals:
                seen_host_globals.add(key)
                glob = llvm.GlobalOp(
                    llvm.LLVMArrayType.from_size_and_type(1, i8),
                    host_var_name,
                    "external",
                )
                glob.attributes["module"] = StringAttr(host_module_name)
                host_global_ops.append(glob)

        # ── ArraySectionOps for multi-dimensional host arrays ─────────────────
        # For each host variable whose module metadata has 'horizontal_dimension'
        # as its first dimension, wrap its HostVarRefOp result in an
        # ArraySectionOp encoding the Fortran slice col_start:col_end for dim 0
        # and 1:<dim_var> for each subsequent dimension.
        array_section_pre_ops = []   # constant-1 op (created at most once)
        array_section_extra_ops = [] # extra HostVarRefOps for dim bounds
        array_section_main_ops = []  # ArraySectionOps
        one_const_for_sections = None

        for i, (arg_name, arg_type) in enumerate(zip(callee_input_names, callee_input_types)):
            src = physics_arg_sources[i]
            if src[0] != "host":
                continue
            _, host_var_name, host_module_name = src

            # Look up module variable descriptor to get dimension standard names
            try:
                mod_arg_table = meta_data[host_module_name].getArgTable(host_module_name)
                host_var_desc = mod_arg_table.getFunctionArgument(host_var_name)
            except (KeyError, AssertionError):
                continue

            if not host_var_desc.hasAttr("dim_names"):
                continue
            dim_names_list = host_var_desc.getAttr("dim_names")
            if not dim_names_list or dim_names_list[0] != "horizontal_dimension":
                continue

            # col_start and col_end must be non-host block args
            if "col_start" not in block_arg_map or "col_end" not in block_arg_map:
                continue

            lowers = [block_arg_map["col_start"]]
            uppers = [block_arg_map["col_end"]]

            # Build bounds for remaining (vertical) dimensions
            valid = True
            for dim_std_name in dim_names_list[1:]:
                if dim_std_name not in host_var_map:
                    valid = False
                    break
                dim_var_name, dim_module_name = host_var_map[dim_std_name]

                if dim_var_name in host_name_to_ref_result:
                    dim_upper_ref = host_name_to_ref_result[dim_var_name]
                else:
                    # Need a fresh HostVarRefOp for this dimension variable
                    dim_ref_op = HostVarRefOp(
                        dim_var_name, dim_module_name,
                        TypeConversions.getBaseType("integer"),
                    )
                    array_section_extra_ops.append(dim_ref_op)
                    host_name_to_ref_result[dim_var_name] = dim_ref_op.res
                    dim_upper_ref = dim_ref_op.res
                    # Register as a global for 'use' statement generation
                    key = (dim_var_name, dim_module_name)
                    if key not in seen_host_globals:
                        seen_host_globals.add(key)
                        dim_glob = llvm.GlobalOp(
                            llvm.LLVMArrayType.from_size_and_type(1, i8),
                            dim_var_name,
                            "external",
                        )
                        dim_glob.attributes["module"] = StringAttr(dim_module_name)
                        host_global_ops.append(dim_glob)

                if one_const_for_sections is None:
                    one_const_for_sections = arith.ConstantOp.from_int_and_width(1, 32)
                    array_section_pre_ops.append(one_const_for_sections)

                lowers.append(one_const_for_sections.result)
                uppers.append(dim_upper_ref)

            if not valid or len(lowers) < 2:
                continue

            section = ArraySectionOp(
                host_var_ref_results[arg_name],
                lowers,
                uppers,
            )
            array_section_main_ops.append(section)
            host_var_ref_results[arg_name] = section.res

        array_section_ops = array_section_pre_ops + array_section_extra_ops + array_section_main_ops

        # Build call args in callee order (mix of host refs / sections and block args).
        call_args = []
        for i, arg_name in enumerate(callee_input_names):
            if physics_arg_sources[i][0] == "host":
                call_args.append(host_var_ref_results[arg_name])
            else:
                call_args.append(block_arg_map[arg_name])

        # ── Body ops ──────────────────────────────────────────────────────────
        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_arg, [])

        suite_name_eq = StringEqOp(suite_name_arg, suite_name)
        suite_part_eq = StringEqOp(suite_part_arg, suite_part)

        call_op = func.CallOp(suite_callee, call_args, callee_output_types)

        copy_ops = []
        for idx, ret_type in enumerate(callee_output_types):
            if ret_type == errmsg_type:
                copy_ops.append(memref.CopyOp(call_op.results[idx], errmsg_arg))
            elif ret_type == errflg_type:
                copy_ops.append(memref.CopyOp(call_op.results[idx], errflg_arg))

        write_suite_part = WriteErrMsgOp(
            errmsg_arg, suite_part_arg,
            "No suite part named ",
            f" found in suite {suite_name}",
        )
        one_inner = arith.ConstantOp.from_int_and_width(1, 32)
        store_errflg_inner = memref.StoreOp.get(one_inner, errflg_arg, [])

        inner_if = scf.IfOp(
            suite_part_eq.res, [],
            [call_op] + copy_ops + [scf.YieldOp()],
            [write_suite_part, one_inner, store_errflg_inner, scf.YieldOp()],
        )

        write_suite_name = WriteErrMsgOp(
            errmsg_arg, suite_name_arg,
            "No suite named ",
            "found",
        )
        one_outer = arith.ConstantOp.from_int_and_width(1, 32)
        store_errflg_outer = memref.StoreOp.get(one_outer, errflg_arg, [])

        outer_if = scf.IfOp(
            suite_name_eq.res, [],
            [suite_part_eq, inner_if, scf.YieldOp()],
            [write_suite_name, one_outer, store_errflg_outer, scf.YieldOp()],
        )

        ret_op = func.ReturnOp(errmsg_arg, errflg_arg)

        new_block.add_ops([
            err_const, store_errflg,
            *host_var_ref_ops,
            *array_section_ops,
            suite_name_eq,
            outer_if,
            ret_op,
        ])

        body = Region()
        body.add_block(new_block)

        fn_type = builtin.FunctionType.from_lists(
            all_block_types,
            [errmsg_type, errflg_type],
        )
        cap_fn = func.FuncOp(fn_name, fn_type, body, visibility="public")
        decl = func.FuncOp.external(suite_callee, callee_input_types, callee_output_types)
        decl.attributes["module"] = StringAttr(callee_module)
        return cap_fn, decl, host_global_ops

    def _generate_ccpp_cap_module(self, suite_name, suite_desc, meta_data, public_fns):
        """Build the CCPP cap ModuleOp for one suite.

        Generates the lifecycle subroutines inside a module named
        ``<snake_case>_ccpp_cap``.  Produces:
          - ``<CamelCase>_ccpp_physics_initialize``
          - ``<CamelCase>_ccpp_physics_finalize``
          - ``<CamelCase>_ccpp_physics_timestep_initial``
          - ``<CamelCase>_ccpp_physics_timestep_final``
          - ``<CamelCase>_ccpp_physics_run``
        """
        camel_name = self._derive_camel_case_name(suite_name)

        scheme_names = [
            scheme.attributes["name"]
            for group in suite_desc
            for scheme in group
        ]

        char_base = TypeConversions.getBaseType("character")   # i8
        int_base = TypeConversions.getBaseType("integer")      # i32
        suite_name_type = memref.MemRefType(char_base, [DYNAMIC_INDEX])
        errmsg_type = memref.MemRefType(char_base, [512])
        errflg_type = memref.MemRefType(int_base, [])

        # Shared kwargs for _generate_lifecycle_fn and _generate_run_fn
        common = dict(
            suite_name=suite_name,
            suite_name_type=suite_name_type,
            errmsg_type=errmsg_type,
            errflg_type=errflg_type,
            char_base=char_base,
            int_base=int_base,
            public_fns=public_fns,
        )

        # Each entry: (fn suffix, table postfix, callee suffix, suite_part or None)
        # suite_part=None  → simple lifecycle dispatch (_generate_lifecycle_fn)
        # suite_part=str   → physics run dispatch (_generate_run_fn)
        lifecycle_specs = [
            ("_ccpp_physics_initialize", "_init",     "_suite_initialize", None),
            ("_ccpp_physics_finalize",   "_finalize",  "_suite_finalize",  None),
            ("_ccpp_physics_timestep_initial", None, "_suite_timestep_initial", None),
            ("_ccpp_physics_timestep_final",   None, "_suite_timestep_final",   None),
            ("_ccpp_physics_run",               None, "_suite_physics",    "physics"),
        ]

        all_globals: list = []
        all_definitions: list = []
        all_declarations: list = []

        for fn_suffix, table_postfix, callee_suffix, suite_part in lifecycle_specs:
            suite_callee = suite_name + callee_suffix
            if suite_part is not None:
                # Physics run: nested suite_name + suite_part dispatch
                cap_fn, decl, host_global_ops = self._generate_run_fn(
                    fn_name=camel_name + fn_suffix,
                    suite_part=suite_part,
                    suite_callee=suite_callee,
                    scheme_names=scheme_names,
                    meta_data=meta_data,
                    **common,
                )
                all_globals.extend(host_global_ops)
            elif table_postfix is not None:
                # Derive return types from the scheme arg tables in the metadata
                call_ret_types = self._get_suite_lifecycle_return_types(
                    scheme_names, meta_data, table_postfix
                )
                cap_fn, decl = self._generate_lifecycle_fn(
                    fn_name=camel_name + fn_suffix,
                    suite_callee=suite_callee,
                    call_ret_types=call_ret_types,
                    **common,
                )
            else:
                # No scheme arg tables for this phase (e.g. timestep_initial).
                # Read the return types directly from the already-generated
                # suite cap function in the IR.
                assert suite_callee in public_fns, (
                    f"Suite callee '{suite_callee}' not found; "
                    f"available: {sorted(public_fns)}"
                )
                _callee_mod, call_ret_types, _, _ = public_fns[suite_callee]
                cap_fn, decl = self._generate_lifecycle_fn(
                    fn_name=camel_name + fn_suffix,
                    suite_callee=suite_callee,
                    call_ret_types=call_ret_types,
                    **common,
                )
            all_definitions.append(cap_fn)
            all_declarations.append(decl)

        # Generate ccpp_physics_suite_list as a func.FuncOp using upstream ops.
        # The suites argument is memref<memref<?xi8>>: a reference to an
        # allocatable character(len=*) array, matching Fortran intent(out).
        #
        # For each suite name we:
        #   1. Create an llvm.GlobalOp string constant (like state strings in suite_cap).
        #   2. Alloc a memref<?xi8> string buffer (→ Fortran allocate(suites(N))).
        #   3. Annotate the AllocOp with 'string_src' so the printer emits the
        #      assignment (suites(i) = str_<suite_name>).
        #   4. Store the memref<?xi8> into the allocatable arg.
        inner_char_type = memref.MemRefType(i8, [DYNAMIC_INDEX])
        allocatable_type = memref.MemRefType(inner_char_type, [])
        suite_list_block = Block(arg_types=[allocatable_type])
        suite_list_block.args[0].name_hint = "suites"

        suite_names_list = [suite_name]  # one suite per cap module
        body_ops = []
        for sn in suite_names_list:
            str_global_name = f"str_{sn}"
            str_len = len(sn)
            arr_type = llvm.LLVMArrayType.from_size_and_type(str_len, i8)

            # Module-level string constant for the suite name
            all_globals.append(
                llvm.GlobalOp(arr_type, str_global_name, "internal",
                              constant=True, value=StringAttr(sn))
            )

            # Allocate the memref<?xi8> string buffer.
            # Annotate with 'string_src' so the Fortran printer knows which
            # module-level global to emit as the assignment RHS.
            str_len_const = arith.ConstantOp(IntegerAttr(str_len, IndexType()), IndexType())
            str_alloc = memref.AllocOp([str_len_const.result], [], inner_char_type)
            str_alloc.attributes["string_src"] = StringAttr(str_global_name)

            # Store the memref<?xi8> reference into the allocatable argument
            store_ref_op = memref.StoreOp.get(str_alloc.memref, suite_list_block.args[0], [])
            body_ops.extend([str_len_const, str_alloc, store_ref_op])

        suite_list_block.add_ops([*body_ops, func.ReturnOp()])
        suite_list_region = Region()
        suite_list_region.add_block(suite_list_block)
        suite_list_fn = func.FuncOp(
            "ccpp_physics_suite_list",
            builtin.FunctionType.from_lists([allocatable_type], []),
            suite_list_region,
            visibility="public",
        )
        all_definitions.append(suite_list_fn)

        module_ops = all_globals + all_definitions + all_declarations

        mod_base = suite_name[:-6] if suite_name.endswith("_suite") else suite_name
        mod_name = mod_base + "_ccpp_cap"

        return builtin.ModuleOp(
            module_ops,
            sym_name=builtin.StringAttr(mod_name),
        )

    def apply(self, ctx: Context, op: builtin.ModuleOp) -> None:
        ccpp_mod = self.find_ccpp_module(op.body.block.ops)
        assert ccpp_mod is not None

        # Build Python descriptor objects from the CCPP metadata IR
        bmdd = BuildMetaDataDescriptions()
        bmdd.traverse(ccpp_mod)
        meta_data_descriptions = bmdd.meta_data

        # Build the suite hierarchy descriptors
        bsd = BuildSchemeDescription()
        bsd.traverse(ccpp_mod)
        suite_descriptions = bsd.schemes

        # Collect public functions from suite cap modules already in the IR
        # (generated by generate-suite-cap, which runs before this pass)
        public_fns = self._collect_public_suite_functions(op.body.block.ops)

        # Generate one CCPP cap module per suite
        for suite_name, suite_desc in suite_descriptions.items():
            cap_mod = self._generate_ccpp_cap_module(
                suite_name, suite_desc, meta_data_descriptions, public_fns
            )
            op.body.block.add_op(cap_mod)

