from dataclasses import dataclass

from xdsl.dialects import builtin, memref, func, arith, scf
from xdsl.dialects.builtin import i8, StringAttr, DYNAMIC_INDEX
from xdsl.context import Context
from xdsl.passes import ModulePass
from xdsl.ir import Block, Region
from xdsl.utils.hints import isa

from xdsl_ccpp.dialects import ccpp_utils
from xdsl_ccpp.dialects.ccpp_utils import StringEqOp

from xdsl_ccpp.transforms.util.ccpp_descriptors import BuildMetaDataDescriptions, BuildSchemeDescription
from xdsl_ccpp.transforms.util.typing import TypeConversions


@dataclass(frozen=True)
class CCPPCAP(ModulePass):
    """MLIR pass that generates the CCPP physics cap dispatcher module.

    Runs after generate-suite-cap.  For each suite found in the ccpp module,
    generates lifecycle dispatcher subroutines that:
      1. Take ``suite_name`` (assumed-length character), ``errmsg``, and
         ``errflg`` as arguments.
      2. Compare ``suite_name`` against the suite's name literal.
      3. If the name matches, delegate to the corresponding suite cap
         subroutine (generated by generate-suite-cap).

    Currently generates ``_initialize`` and ``_finalize`` dispatchers.
    Output is a named ModuleOp (e.g. ``hello_world_ccpp_cap``) inserted into
    the top-level module alongside the suite cap modules.
    """

    name = "generate-ccpp-cap"

    def find_ccpp_module(self, ops):
        """Return the named 'ccpp' ModuleOp from the given op list, or None."""
        for op in ops:
            if isa(op, builtin.ModuleOp) and op.sym_name is not None and op.sym_name.data == "ccpp":
                return op
        return None

    def _collect_public_suite_functions(self, ops):
        """Scan all named ModuleOps in ops and return a map of public function info.

        Looks at every named sub-ModuleOp (e.g. ``hello_world_suite_cap``) that
        is already present in the IR (generated by earlier passes) and records
        every public subroutine definition it contains.

        Returns:
            dict mapping function_name → (module_name, output_types) where
            output_types is the list of MLIR result types for that function.
            Used both to resolve callee module names and to derive call return
            types for lifecycle phases that have no scheme arg tables.
        """
        public_fns = {}
        for op in ops:
            if not (isa(op, builtin.ModuleOp) and op.sym_name is not None):
                continue
            mod_name = op.sym_name.data
            for child in op.body.block.ops:
                if (
                    isa(child, func.FuncOp)
                    and not child.is_declaration
                    and child.sym_visibility is not None
                    and child.sym_visibility.data == "public"
                ):
                    public_fns[child.sym_name.data] = (
                        mod_name,
                        list(child.function_type.outputs),
                    )
        return public_fns

    def _derive_camel_case_name(self, suite_name: str) -> str:
        """Convert a snake_case suite name to CamelCase, stripping any '_suite' suffix.

        Examples:
            hello_world_suite → HelloWorld
            my_suite          → My
        """
        name = suite_name
        if name.endswith("_suite"):
            name = name[:-6]
        return "".join(word.capitalize() for word in name.split("_"))

    def _get_suite_lifecycle_return_types(self, scheme_names, meta_data, table_postfix):
        """Derive the ordered return types of a suite lifecycle subroutine.

        Mirrors the alloc_ops ordering that generate-suite-cap uses: iterates
        out args from each scheme's arg table (identified by ``table_postfix``,
        e.g. ``"_init"`` or ``"_finalize"``) in metadata order, deduplicating
        by argument name.

        Returns a list of MLIR MemRefType values (one per unique out arg).
        """
        all_out_args = {}
        for scheme_name in scheme_names:
            table_name = scheme_name + table_postfix
            assert table_name in meta_data[scheme_name].arg_tables, \
                f"No '{table_postfix}' arg table found for scheme '{scheme_name}'"
            arg_table = meta_data[scheme_name].getArgTable(table_name)
            for fn_arg in arg_table.getFunctionArguments():
                if fn_arg.getAttr("intent") == "out" and fn_arg.name not in all_out_args:
                    all_out_args[fn_arg.name] = fn_arg

        return [
            TypeConversions.convert(
                arg.getAttr("type"),
                arg.getAttr("kind") if arg.hasAttr("kind") else None,
                0,
            )
            for arg in all_out_args.values()
        ]

    def _generate_lifecycle_fn(
        self, fn_name, suite_name, suite_callee, call_ret_types,
        suite_name_type, errmsg_type, errflg_type, char_base, int_base,
        public_fns,
    ):
        """Build one CCPP cap lifecycle FuncOp and its external declaration.

        Asserts that ``suite_callee`` is listed in ``public_fns`` (the map of
        public functions collected from the already-generated suite cap modules)
        and attaches the owning module name to the external declaration as the
        ``module`` attribute.  The Fortran printer uses this to emit a
        ``use <module>, only: <proc>`` statement in the generated module.

        The generated subroutine:
          1. Allocates local errmsg and errflg.
          2. Initialises errflg = 0.
          3. Compares suite_name against the suite name literal.
          4. If they match, calls suite_callee and copies the results back.

        Returns ``(FuncOp, external_decl_FuncOp)``.
        """
        assert suite_callee in public_fns, (
            f"Suite callee '{suite_callee}' not found among public suite cap "
            f"functions; available: {sorted(public_fns)}"
        )
        callee_module, _callee_output_types = public_fns[suite_callee]
        errmsg_alloc = memref.AllocaOp.get(char_base, shape=[512])
        errmsg_alloc.memref.name_hint = "errmsg"
        errflg_alloc = memref.AllocaOp.get(int_base, shape=[])
        errflg_alloc.memref.name_hint = "errflg"

        new_block = Block(arg_types=[suite_name_type])
        new_block.args[0].name_hint = "suite_name"

        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_alloc, [])

        string_eq_op = StringEqOp(new_block.args[0], suite_name)

        call_op = func.CallOp(suite_callee, [], call_ret_types)

        copy_ops = []
        for idx, ret_type in enumerate(call_ret_types):
            if ret_type == errmsg_type:
                copy_ops.append(memref.CopyOp(call_op.results[idx], errmsg_alloc))
            elif ret_type == errflg_type:
                copy_ops.append(memref.CopyOp(call_op.results[idx], errflg_alloc))

        if_op = scf.IfOp(
            string_eq_op.res, [],
            [call_op] + copy_ops + [scf.YieldOp()],
        )

        ret_op = func.ReturnOp(errmsg_alloc, errflg_alloc)

        new_block.add_ops([
            errmsg_alloc, errflg_alloc,
            err_const, store_errflg,
            string_eq_op,
            if_op,
            ret_op,
        ])

        body = Region()
        body.add_block(new_block)

        fn_type = builtin.FunctionType.from_lists(
            [suite_name_type],
            [errmsg_type, errflg_type],
        )
        cap_fn = func.FuncOp(fn_name, fn_type, body, visibility="public")
        decl = func.FuncOp.external(suite_callee, [], call_ret_types)
        # Record which module owns suite_callee so the Fortran printer can
        # emit the correct 'use <module>, only: <proc>' statement.
        decl.attributes["module"] = StringAttr(callee_module)
        return cap_fn, decl

    def _generate_ccpp_cap_module(self, suite_name, suite_desc, meta_data, public_fns):
        """Build the CCPP cap ModuleOp for one suite.

        Generates the lifecycle subroutines inside a module named
        ``<snake_case>_ccpp_cap``.  Currently produces:
          - ``<CamelCase>_ccpp_physics_initialize``
          - ``<CamelCase>_ccpp_physics_finalize``
        """
        camel_name = self._derive_camel_case_name(suite_name)

        scheme_names = [
            scheme.attributes["name"]
            for group in suite_desc
            for scheme in group
        ]

        char_base = TypeConversions.getBaseType("character")   # i8
        int_base = TypeConversions.getBaseType("integer")      # i32
        suite_name_type = memref.MemRefType(char_base, [DYNAMIC_INDEX])
        errmsg_type = memref.MemRefType(char_base, [512])
        errflg_type = memref.MemRefType(int_base, [])

        # Shared kwargs for _generate_lifecycle_fn
        common = dict(
            suite_name=suite_name,
            suite_name_type=suite_name_type,
            errmsg_type=errmsg_type,
            errflg_type=errflg_type,
            char_base=char_base,
            int_base=int_base,
            public_fns=public_fns,
        )

        # Each entry: (generated fn name suffix, table postfix, suite callee suffix)
        lifecycle_specs = [
            ("_ccpp_physics_initialize", "_init",     "_suite_initialize"),
            ("_ccpp_physics_finalize",   "_finalize",  "_suite_finalize"),
            ("_ccpp_physics_timestep_initial",   None,  "_suite_timestep_initial"),
            ("_ccpp_physics_timestep_final",   None,  "_suite_timestep_final"),
        ]

        module_ops = []
        for fn_suffix, table_postfix, callee_suffix in lifecycle_specs:
            suite_callee = suite_name + callee_suffix
            if table_postfix is not None:
                # Derive return types from the scheme arg tables in the metadata
                call_ret_types = self._get_suite_lifecycle_return_types(
                    scheme_names, meta_data, table_postfix
                )
            else:
                # No scheme arg tables for this phase (e.g. timestep_initial).
                # Read the return types directly from the already-generated
                # suite cap function in the IR.
                assert suite_callee in public_fns, (
                    f"Suite callee '{suite_callee}' not found; "
                    f"available: {sorted(public_fns)}"
                )
                _callee_mod, call_ret_types = public_fns[suite_callee]
            cap_fn, decl = self._generate_lifecycle_fn(
                fn_name=camel_name + fn_suffix,
                suite_callee=suite_callee,
                call_ret_types=call_ret_types,
                **common,
            )
            module_ops.extend([cap_fn, decl])

        mod_base = suite_name[:-6] if suite_name.endswith("_suite") else suite_name
        mod_name = mod_base + "_ccpp_cap"

        return builtin.ModuleOp(
            module_ops,
            sym_name=builtin.StringAttr(mod_name),
        )

    def apply(self, ctx: Context, op: builtin.ModuleOp) -> None:
        ccpp_mod = self.find_ccpp_module(op.body.block.ops)
        assert ccpp_mod is not None

        # Build Python descriptor objects from the CCPP metadata IR
        bmdd = BuildMetaDataDescriptions()
        bmdd.traverse(ccpp_mod)
        meta_data_descriptions = bmdd.meta_data

        # Build the suite hierarchy descriptors
        bsd = BuildSchemeDescription()
        bsd.traverse(ccpp_mod)
        suite_descriptions = bsd.schemes

        # Collect public functions from suite cap modules already in the IR
        # (generated by generate-suite-cap, which runs before this pass)
        public_fns = self._collect_public_suite_functions(op.body.block.ops)

        # Generate one CCPP cap module per suite
        for suite_name, suite_desc in suite_descriptions.items():
            cap_mod = self._generate_ccpp_cap_module(
                suite_name, suite_desc, meta_data_descriptions, public_fns
            )
            op.body.block.add_op(cap_mod)

