from dataclasses import dataclass

from xdsl.dialects import builtin, memref, func, arith, scf
from xdsl.dialects.builtin import i8, StringAttr, DYNAMIC_INDEX
from xdsl.context import Context
from xdsl.passes import ModulePass
from xdsl.ir import Block, Region
from xdsl.utils.hints import isa

from xdsl_ccpp.dialects import ccpp_utils
from xdsl_ccpp.dialects.ccpp_utils import StringEqOp

from xdsl_ccpp.transforms.util.ccpp_descriptors import BuildMetaDataDescriptions, BuildSchemeDescription
from xdsl_ccpp.transforms.util.typing import TypeConversions


@dataclass(frozen=True)
class CCPPCAP(ModulePass):
    """MLIR pass that generates the CCPP physics cap dispatcher module.

    Runs after generate-suite-cap.  For each suite found in the ccpp module,
    generates a ``<CamelCase>_ccpp_physics_initialize`` subroutine that:
      1. Takes ``suite_name`` (assumed-length character), ``errmsg``, and
         ``errflg`` as arguments.
      2. Compares ``suite_name`` against the suite's name literal.
      3. If the name matches, calls the corresponding suite cap initialize
         subroutine (generated by generate-suite-cap).

    Output is a named ModuleOp (e.g. ``hello_world_ccpp_cap``) inserted into
    the top-level module alongside the suite cap modules.
    """

    name = "generate-ccpp-cap"

    def find_ccpp_module(self, ops):
        """Return the named 'ccpp' ModuleOp from the given op list, or None."""
        for op in ops:
            if isa(op, builtin.ModuleOp) and op.sym_name is not None and op.sym_name.data == "ccpp":
                return op
        return None

    def _derive_camel_case_name(self, suite_name: str) -> str:
        """Convert a snake_case suite name to CamelCase, stripping any '_suite' suffix.

        Examples:
            hello_world_suite → HelloWorld
            my_suite          → My
        """
        name = suite_name
        if name.endswith("_suite"):
            name = name[:-6]
        return "".join(word.capitalize() for word in name.split("_"))

    def _get_suite_init_return_types(self, scheme_names, meta_data):
        """Derive the ordered return types of ``{suite}_suite_initialize``.

        Mirrors the alloc_ops ordering that generate-suite-cap uses when
        building the _initialize subroutine: iterates out args from each
        scheme's ``_init`` arg table in metadata order, deduplicating by name.

        Returns a list of MLIR MemRefType values (one per unique out arg).
        """
        all_out_args = {}
        for scheme_name in scheme_names:
            init_table_name = scheme_name + "_init"
            assert init_table_name in meta_data[scheme_name].arg_tables, \
                f"No _init arg table found for scheme '{scheme_name}'"
            arg_table = meta_data[scheme_name].getArgTable(init_table_name)
            for fn_arg in arg_table.getFunctionArguments():
                if fn_arg.getAttr("intent") == "out" and fn_arg.name not in all_out_args:
                    all_out_args[fn_arg.name] = fn_arg

        return [
            TypeConversions.convert(
                arg.getAttr("type"),
                arg.getAttr("kind") if arg.hasAttr("kind") else None,
                0,
            )
            for arg in all_out_args.values()
        ]

    def _generate_ccpp_cap_module(self, suite_name, suite_desc, meta_data):
        """Build the CCPP cap ModuleOp for one suite.

        Generates a single subroutine named ``<CamelCase>_ccpp_physics_initialize``
        inside a module named ``<snake_case>_ccpp_cap``.
        """
        camel_name = self._derive_camel_case_name(suite_name)
        fn_name = f"{camel_name}_ccpp_physics_initialize"

        # Collect scheme names in suite order (needed to derive call return types)
        scheme_names = [
            scheme.attributes["name"]
            for group in suite_desc
            for scheme in group
        ]

        # suite_name argument type: assumed-length character buffer
        char_base = TypeConversions.getBaseType("character")   # i8
        int_base = TypeConversions.getBaseType("integer")      # i32
        suite_name_type = memref.MemRefType(char_base, [DYNAMIC_INDEX])

        # errmsg and errflg are locally allocated output args
        errmsg_alloc = memref.AllocaOp.get(char_base, shape=[512])
        errmsg_alloc.memref.name_hint = "errmsg"
        errflg_alloc = memref.AllocaOp.get(int_base, shape=[])
        errflg_alloc.memref.name_hint = "errflg"

        # Block arg: suite_name (in)
        new_block = Block(arg_types=[suite_name_type])
        new_block.args[0].name_hint = "suite_name"

        # Initialise errflg = 0
        err_const = arith.ConstantOp.from_int_and_width(0, 32)
        store_errflg = memref.StoreOp.get(err_const, errflg_alloc, [])

        # Compare suite_name against the suite's literal name
        string_eq_op = StringEqOp(new_block.args[0], suite_name)

        # Determine call return types from the suite's _init arg table
        init_fn_name = f"{suite_name}_suite_initialize"
        call_ret_types = self._get_suite_init_return_types(scheme_names, meta_data)

        # Build the suite initialize call and copy results back to local storage
        call_op = func.CallOp(init_fn_name, [], call_ret_types)

        # Match each call result to its local alloca by type/name
        errmsg_type = memref.MemRefType(char_base, [512])
        errflg_type = memref.MemRefType(int_base, [])
        copy_ops = []
        for idx, ret_type in enumerate(call_ret_types):
            if ret_type == errmsg_type:
                copy_ops.append(memref.CopyOp(call_op.results[idx], errmsg_alloc))
            elif ret_type == errflg_type:
                copy_ops.append(memref.CopyOp(call_op.results[idx], errflg_alloc))

        # Guard the call: only execute when suite_name matches
        if_op = scf.IfOp(
            string_eq_op.res, [],
            [call_op] + copy_ops + [scf.YieldOp()],
        )

        ret_op = func.ReturnOp(errmsg_alloc, errflg_alloc)

        new_block.add_ops([
            errmsg_alloc, errflg_alloc,
            err_const, store_errflg,
            string_eq_op,
            if_op,
            ret_op,
        ])

        body = Region()
        body.add_block(new_block)

        fn_type = builtin.FunctionType.from_lists(
            [suite_name_type],
            [errmsg_type, errflg_type],
        )
        cap_fn = func.FuncOp(fn_name, fn_type, body, visibility="public")

        # External declaration for the suite's initialize function
        suite_init_decl = func.FuncOp.external(init_fn_name, [], call_ret_types)

        # Derive module name: hello_world_suite → hello_world_ccpp_cap
        mod_base = suite_name[:-6] if suite_name.endswith("_suite") else suite_name
        mod_name = mod_base + "_ccpp_cap"

        return builtin.ModuleOp(
            [cap_fn, suite_init_decl],
            sym_name=builtin.StringAttr(mod_name),
        )

    def apply(self, ctx: Context, op: builtin.ModuleOp) -> None:
        ccpp_mod = self.find_ccpp_module(op.body.block.ops)
        assert ccpp_mod is not None

        # Build Python descriptor objects from the CCPP metadata IR
        bmdd = BuildMetaDataDescriptions()
        bmdd.traverse(ccpp_mod)
        meta_data_descriptions = bmdd.meta_data

        # Build the suite hierarchy descriptors
        bsd = BuildSchemeDescription()
        bsd.traverse(ccpp_mod)
        suite_descriptions = bsd.schemes

        # Generate one CCPP cap module per suite
        for suite_name, suite_desc in suite_descriptions.items():
            cap_mod = self._generate_ccpp_cap_module(
                suite_name, suite_desc, meta_data_descriptions
            )
            op.body.block.add_op(cap_mod)

